/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as BenchmarkRouteImport } from "./routes/benchmark"
import { Route as IndexRouteImport } from "./routes/index"

const BenchmarkRoute = BenchmarkRouteImport.update({
  id: "/benchmark",
  path: "/benchmark",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/benchmark": typeof BenchmarkRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/benchmark": typeof BenchmarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/benchmark": typeof BenchmarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/benchmark"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/benchmark"
  id: "__root__" | "/" | "/benchmark"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarkRoute: typeof BenchmarkRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/benchmark": {
      id: "/benchmark"
      path: "/benchmark"
      fullPath: "/benchmark"
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarkRoute: BenchmarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
